#ifndef __LEFT_PATH_FACTORY__
#define __LEFT_PATH_FACTORY__

#include "AbstractStageFactory.hpp"

class LeftPathFactory : public AbstractStageFactory {
 public:
    LeftPathFactory(BaseCharacter* user) : AbstractStageFactory(user) { }
    virtual vector<BaseCharacter*> getStage1() override {return vector<BaseCharacter*>{player, new Zombies(1), new Zombies(1), new Zombies(0)};}
    virtual vector<BaseCharacter*> getStage2() override {return vector<BaseCharacter*>{player, new Zombies(1), new Zombies(1), new Fairies(1), new Fairies(1), new Fairies(0)};}
    virtual vector<BaseCharacter*> getStage3() override {return vector<BaseCharacter*>{player, new Zombies(1), new Zombies(1), new Zombies(1), new Fairies(1), new Fairies(1), new Goblins(1), new Goblins(0)};}
    virtual vector<BaseCharacter*> getStage4() override {return vector<BaseCharacter*>{player, new SpikesDecorator(new Zombies(2)), new SpikesDecorator(new Zombies(2)), new Zombies(2), new Zombies(2)};}
    virtual vector<BaseCharacter*> getStage5() override {return vector<BaseCharacter*>{player, new SpikesDecorator(new Zombies(2)), new SpikesDecorator(new Zombies(2)), new SpikesDecorator(new Zombies(2)), new SpikesDecorator(new Zombies(2)), new DrainDecorator(new Fairies(2)), new DrainDecorator(new Fairies(2)), new DrainDecorator(new Fairies(2)), new DrainDecorator(new Fairies(2))};}
    virtual vector<BaseCharacter*> getStage6() override {return vector<BaseCharacter*>{player, new SpikesDecorator(new Zombies(2)), new SpikesDecorator(new Zombies(2)), new SpikesDecorator(new Zombies(2)), new SpikesDecorator(new Zombies(3)), new DrainDecorator(new Fairies(2)), new DrainDecorator(new Fairies(2)), new DrainDecorator(new Fairies(2)), new DrainDecorator(new Fairies(3)), new CriticalDecorator(new Goblins(2)), new CriticalDecorator(new Goblins(2)), new CriticalDecorator(new Goblins(2)), new CriticalDecorator(new Goblins(3))};}
    virtual vector<BaseCharacter*> getStage7() override {return vector<BaseCharacter*>{player, new SpikesDecorator(new Zombies(3)), new SpikesDecorator(new Zombies(3)), new SpikesDecorator(new Zombies(3)), new DrainDecorator(new Fairies(3)), new DrainDecorator(new Fairies(3)), new DrainDecorator(new Fairies(3)), new CriticalDecorator(new Goblins(3)), new CriticalDecorator(new Goblins(3)), new CriticalDecorator(new Goblins(3))};}
    virtual vector<BaseCharacter*> getStage8() override {return vector<BaseCharacter*>{player, new ArmorDecorator(new SpikesDecorator(new Zombies(4))), new ArmorDecorator(new SpikesDecorator(new Zombies(4))), new ArmorDecorator(new SpikesDecorator(new Zombies(4))), new CriticalDecorator(new ArmorDecorator(new SpikesDecorator(new Zombies(3)))), new CriticalDecorator(new ArmorDecorator(new SpikesDecorator(new Zombies(3)))), new CriticalDecorator(new ArmorDecorator(new SpikesDecorator(new Zombies(3)))), new DrainDecorator(new SpikesDecorator(new Fairies(4))), new DrainDecorator(new SpikesDecorator(new Fairies(4))), new DrainDecorator(new SpikesDecorator(new Fairies(4))), new CriticalDecorator(new DodgeDecorator(new Goblins(4))), new CriticalDecorator(new DodgeDecorator(new Goblins(4))), new CriticalDecorator(new DodgeDecorator(new Goblins(4))), new CriticalDecorator(new DodgeDecorator(new ArmorDecorator(new Goblins(3)))), new CriticalDecorator(new DodgeDecorator(new ArmorDecorator(new Goblins(3)))), new CriticalDecorator(new DodgeDecorator(new ArmorDecorator(new Goblins(3))))};}
    virtual vector<BaseCharacter*> getStage9() override {return vector<BaseCharacter*>{player, new Zombies(5), new Fairies(5), new Goblins(5), new CriticalDecorator(new ArmorDecorator(new Zombies(3))), new CriticalDecorator(new ArmorDecorator(new Zombies(3))), new CriticalDecorator(new ArmorDecorator(new Zombies(3))), new CriticalDecorator(new ArmorDecorator(new Zombies(3))), new CriticalDecorator(new ArmorDecorator(new Zombies(3))), new CriticalDecorator(new ArmorDecorator(new Zombies(3))), new CriticalDecorator(new ArmorDecorator(new Zombies(3))), new DrainDecorator(new SpikesDecorator(new Fairies(3))), new DrainDecorator(new SpikesDecorator(new Fairies(3))), new DrainDecorator(new SpikesDecorator(new Fairies(3))), new DrainDecorator(new SpikesDecorator(new Fairies(3))), new DrainDecorator(new SpikesDecorator(new Fairies(3))), new DrainDecorator(new SpikesDecorator(new Fairies(3))), new DrainDecorator(new SpikesDecorator(new Fairies(3))), new CriticalDecorator(new DodgeDecorator(new Goblins(3))), new CriticalDecorator(new DodgeDecorator(new Goblins(3))), new CriticalDecorator(new DodgeDecorator(new Goblins(3))), new CriticalDecorator(new DodgeDecorator(new Goblins(3))), new CriticalDecorator(new DodgeDecorator(new Goblins(3))), new CriticalDecorator(new DodgeDecorator(new Goblins(3))), new CriticalDecorator(new DodgeDecorator(new Goblins(3)))};}
    virtual vector<BaseCharacter*> getStage10() override {return vector<BaseCharacter*>{player, new CriticalDecorator(new DrainDecorator(new DodgeDecorator(new ArmorDecorator(new SpikesDecorator(new Goblins(6)))))), new CriticalDecorator(new ArmorDecorator(new Zombies(3))), new CriticalDecorator(new ArmorDecorator(new Zombies(3))), new CriticalDecorator(new ArmorDecorator(new Zombies(3))), new CriticalDecorator(new ArmorDecorator(new Zombies(3))), new CriticalDecorator(new ArmorDecorator(new Zombies(3))), new CriticalDecorator(new ArmorDecorator(new Zombies(3))), new CriticalDecorator(new ArmorDecorator(new Zombies(3))), new CriticalDecorator(new ArmorDecorator(new Zombies(3))), new CriticalDecorator(new ArmorDecorator(new Zombies(3))), new CriticalDecorator(new ArmorDecorator(new Zombies(3))), new CriticalDecorator(new ArmorDecorator(new Zombies(3))), new CriticalDecorator(new ArmorDecorator(new Zombies(3))), new DrainDecorator(new SpikesDecorator(new Fairies(3))), new DrainDecorator(new SpikesDecorator(new Fairies(3))), new DrainDecorator(new SpikesDecorator(new Fairies(3))), new DrainDecorator(new SpikesDecorator(new Fairies(3))), new DrainDecorator(new SpikesDecorator(new Fairies(3))), new DrainDecorator(new SpikesDecorator(new Fairies(3))), new DrainDecorator(new SpikesDecorator(new Fairies(3))), new DrainDecorator(new SpikesDecorator(new Fairies(3))), new DrainDecorator(new SpikesDecorator(new Fairies(3))), new DrainDecorator(new SpikesDecorator(new Fairies(3))), new DrainDecorator(new SpikesDecorator(new Fairies(3))), new DrainDecorator(new SpikesDecorator(new Fairies(3))), new CriticalDecorator(new DodgeDecorator(new Goblins(3))), new CriticalDecorator(new DodgeDecorator(new Goblins(3))), new CriticalDecorator(new DodgeDecorator(new Goblins(3))), new CriticalDecorator(new DodgeDecorator(new Goblins(3))), new CriticalDecorator(new DodgeDecorator(new Goblins(3))), new CriticalDecorator(new DodgeDecorator(new Goblins(3))), new CriticalDecorator(new DodgeDecorator(new Goblins(3))), new CriticalDecorator(new DodgeDecorator(new Goblins(3))), new CriticalDecorator(new DodgeDecorator(new Goblins(3))), new CriticalDecorator(new DodgeDecorator(new Goblins(3))), new CriticalDecorator(new DodgeDecorator(new Goblins(3))), new CriticalDecorator(new DodgeDecorator(new Goblins(3)))};}
};

#endif
