#ifndef __LEFT_PATH_FACTORY__
#define __LEFT_PATH_FACTORY__

#include "AbstractStageFactory.hpp"

class LeftPathFactory : public AbstractStageFactory {
 public:
    LeftPathFactory(BaseCharacter* user) : AbstractStageFactory(user) { }
    virtual vector<BaseCharacter*> getStage1() override {return vector<BaseCharacter*>{player, new Zombie(1), new Zombie(1), new Zombie(0)};}
    virtual vector<BaseCharacter*> getStage2() override {return vector<BaseCharacter*>{player, new Zombie(1), new Zombie(1), new Fairy(1), new Fairy(1), new Fairy(0)};}
    virtual vector<BaseCharacter*> getStage3() override {return vector<BaseCharacter*>{player, new Zombie(1), new Zombie(1), new Zombie(1), new Fairy(1), new Fairy(1), new Goblin(1), new Goblin(0)};}
    virtual vector<BaseCharacter*> getStage4() override {return vector<BaseCharacter*>{player, new SpikesDecorator(new Zombie(2)), new SpikesDecorator(new Zombie(2)), new Zombie(2), new Zombie(2)};}
    virtual vector<BaseCharacter*> getStage5() override {return vector<BaseCharacter*>{player, new SpikesDecorator(new Zombie(2)), new SpikesDecorator(new Zombie(2)), new SpikesDecorator(new Zombie(2)), new SpikesDecorator(new Zombie(2)), new DrainDecorator(new Fairy(2)), new DrainDecorator(new Fairy(2)), new DrainDecorator(new Fairy(2)), new DrainDecorator(new Fairy(2))};}
    virtual vector<BaseCharacter*> getStage6() override {return vector<BaseCharacter*>{player, new SpikesDecorator(new Zombie(2)), new SpikesDecorator(new Zombie(2)), new SpikesDecorator(new Zombie(2)), new SpikesDecorator(new Zombie(3)), new DrainDecorator(new Fairy(2)), new DrainDecorator(new Fairy(2)), new DrainDecorator(new Fairy(2)), new DrainDecorator(new Fairy(3)), new CriticalDecorator(new Goblin(2)), new CriticalDecorator(new Goblin(2)), new CriticalDecorator(new Goblin(2)), new CriticalDecorator(new Goblin(3))};}
    virtual vector<BaseCharacter*> getStage7() override {return vector<BaseCharacter*>{player, new SpikesDecorator(new Zombie(3)), new SpikesDecorator(new Zombie(3)), new SpikesDecorator(new Zombie(3)), new DrainDecorator(new Fairy(3)), new DrainDecorator(new Fairy(3)), new DrainDecorator(new Fairy(3)), new CriticalDecorator(new Goblin(3)), new CriticalDecorator(new Goblin(3)), new CriticalDecorator(new Goblin(3))};}
    virtual vector<BaseCharacter*> getStage8() override {return vector<BaseCharacter*>{player, new ArmorDecorator(new SpikesDecorator(new Zombie(4))), new ArmorDecorator(new SpikesDecorator(new Zombie(4))), new ArmorDecorator(new SpikesDecorator(new Zombie(4))), new CriticalDecorator(new ArmorDecorator(new SpikesDecorator(new Zombie(3)))), new CriticalDecorator(new ArmorDecorator(new SpikesDecorator(new Zombie(3)))), new CriticalDecorator(new ArmorDecorator(new SpikesDecorator(new Zombie(3)))), new DrainDecorator(new SpikesDecorator(new Fairy(4))), new DrainDecorator(new SpikesDecorator(new Fairy(4))), new DrainDecorator(new SpikesDecorator(new Fairy(4))), new CriticalDecorator(new DodgeDecorator(new Goblin(4))), new CriticalDecorator(new DodgeDecorator(new Goblin(4))), new CriticalDecorator(new DodgeDecorator(new Goblin(4))), new CriticalDecorator(new DodgeDecorator(new ArmorDecorator(new Goblin(3)))), new CriticalDecorator(new DodgeDecorator(new ArmorDecorator(new Goblin(3)))), new CriticalDecorator(new DodgeDecorator(new ArmorDecorator(new Goblin(3))))};}
    virtual vector<BaseCharacter*> getStage9() override {return vector<BaseCharacter*>{player, new Zombie(5), new Fairy(5), new Goblin(5), new CriticalDecorator(new ArmorDecorator(new Zombie(3))), new CriticalDecorator(new ArmorDecorator(new Zombie(3))), new CriticalDecorator(new ArmorDecorator(new Zombie(3))), new CriticalDecorator(new ArmorDecorator(new Zombie(3))), new CriticalDecorator(new ArmorDecorator(new Zombie(3))), new CriticalDecorator(new ArmorDecorator(new Zombie(3))), new CriticalDecorator(new ArmorDecorator(new Zombie(3))), new DrainDecorator(new SpikesDecorator(new Fairy(3))), new DrainDecorator(new SpikesDecorator(new Fairy(3))), new DrainDecorator(new SpikesDecorator(new Fairy(3))), new DrainDecorator(new SpikesDecorator(new Fairy(3))), new DrainDecorator(new SpikesDecorator(new Fairy(3))), new DrainDecorator(new SpikesDecorator(new Fairy(3))), new DrainDecorator(new SpikesDecorator(new Fairy(3))), new CriticalDecorator(new DodgeDecorator(new Goblin(3))), new CriticalDecorator(new DodgeDecorator(new Goblin(3))), new CriticalDecorator(new DodgeDecorator(new Goblin(3))), new CriticalDecorator(new DodgeDecorator(new Goblin(3))), new CriticalDecorator(new DodgeDecorator(new Goblin(3))), new CriticalDecorator(new DodgeDecorator(new Goblin(3))), new CriticalDecorator(new DodgeDecorator(new Goblin(3)))};}
    virtual vector<BaseCharacter*> getStage10() override {return vector<BaseCharacter*>{player, new CriticalDecorator(new DrainDecorator(new DodgeDecorator(new ArmorDecorator(new SpikesDecorator(new Goblin(6)))))), new CriticalDecorator(new ArmorDecorator(new Zombie(3))), new CriticalDecorator(new ArmorDecorator(new Zombie(3))), new CriticalDecorator(new ArmorDecorator(new Zombie(3))), new CriticalDecorator(new ArmorDecorator(new Zombie(3))), new CriticalDecorator(new ArmorDecorator(new Zombie(3))), new CriticalDecorator(new ArmorDecorator(new Zombie(3))), new CriticalDecorator(new ArmorDecorator(new Zombie(3))), new CriticalDecorator(new ArmorDecorator(new Zombie(3))), new CriticalDecorator(new ArmorDecorator(new Zombie(3))), new CriticalDecorator(new ArmorDecorator(new Zombie(3))), new CriticalDecorator(new ArmorDecorator(new Zombie(3))), new CriticalDecorator(new ArmorDecorator(new Zombie(3))), new DrainDecorator(new SpikesDecorator(new Fairy(3))), new DrainDecorator(new SpikesDecorator(new Fairy(3))), new DrainDecorator(new SpikesDecorator(new Fairy(3))), new DrainDecorator(new SpikesDecorator(new Fairy(3))), new DrainDecorator(new SpikesDecorator(new Fairy(3))), new DrainDecorator(new SpikesDecorator(new Fairy(3))), new DrainDecorator(new SpikesDecorator(new Fairy(3))), new DrainDecorator(new SpikesDecorator(new Fairy(3))), new DrainDecorator(new SpikesDecorator(new Fairy(3))), new DrainDecorator(new SpikesDecorator(new Fairy(3))), new DrainDecorator(new SpikesDecorator(new Fairy(3))), new DrainDecorator(new SpikesDecorator(new Fairy(3))), new CriticalDecorator(new DodgeDecorator(new Goblin(3))), new CriticalDecorator(new DodgeDecorator(new Goblin(3))), new CriticalDecorator(new DodgeDecorator(new Goblin(3))), new CriticalDecorator(new DodgeDecorator(new Goblin(3))), new CriticalDecorator(new DodgeDecorator(new Goblin(3))), new CriticalDecorator(new DodgeDecorator(new Goblin(3))), new CriticalDecorator(new DodgeDecorator(new Goblin(3))), new CriticalDecorator(new DodgeDecorator(new Goblin(3))), new CriticalDecorator(new DodgeDecorator(new Goblin(3))), new CriticalDecorator(new DodgeDecorator(new Goblin(3))), new CriticalDecorator(new DodgeDecorator(new Goblin(3))), new CriticalDecorator(new DodgeDecorator(new Goblin(3)))};}
};

#endif
